import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  uz: {
    dashboard: "Boshqaruv paneli",
    bookings: "Bronlar nazorati",
    customers: "Mijozlar bazasi",
    spaces: "Joylar boshqaruvi",
    parkingLots: "Filiallar",
    reports: "Hisobotlar",
    payments: "Moliya monitoringi",
    notifications: "Xabarlar",
    profile: "Profil",
    logout: "Chiqish",
    amal: "Amal",
    tahrirlash: "Tahrirlash",
    o_chirish: "O'chirish",
    qo_shish: "Qo'shish",
    saqlash: "Saqlash",
    bekor_qilish: "Bekor qilish",
    barchasi: "Barchasi",
    kutilmoqda: "Kutilmoqda",
    faol: "Faol",
    tugallandi: "Tugallandi",
    bekor_qilindi: "Bekor qilindi",
    search: "Qidiruv...",
    revenue: "Jami Tushum",
    occupancy: "Bandlik",
    active_bookings: "Faol Bronlar",
    total_spaces: "Jami Joylar",
    language: "Til",
    theme: "Mavzu",
    dark_mode: "Tungi rejim",
    light_mode: "Kunduzgi rejim",
    error_loading: "Yuklashda xatolik",
    name: "Nomi",
    address: "Manzil",
    working_hours: "Ish vaqti",
    phone: "Telefon",
    email: "Email",
    total: "Jami",
    occupied: "Band",
    available: "Bo'sh",
    price: "Narxi",
    type: "Turi",
    identifier: "Slot raqami",
    status: "Holati",
    car: "Moshina",
    user: "Foydalanuvchi",
    time: "Vaqt",
    sum: "Summa",
    trans_id: "Tranzaksiya ID",
    export: "Eksport",
    map: "Xarita",
    list: "Ro'yxat",
    save_success: "Muvaffaqiyatli saqlandi",
    delete_confirm: "Haqiqatan ham o'chirmoqchimisiz?",
    mark_all_read: "Hammasini o'qish",
    // Profile
    personal_info: "Ma'lumotlar",
    security: "Xavfsizlik",
    statistics: "Statistika",
    first_name: "Ism",
    last_name: "Familiya",
    full_name: "Ism Familiya",
    role: "Sistemadagi rolingiz",
    car_number_type: "Moshina raqami turi / formati",
    individual: "Jismoniy",
    legal_entity: "Yuridik",
    individual_mode: "JISMONIY SHAXS REJIMI",
    legal_mode: "YURIDIK SHAXS REJIMI",
    not_entered: "Kiritilmagan",
    change_password: "Parolni o'zgartirish",
    change_password_desc: "Xavfsizlik tizimini mustahkamlash uchun parolni vaqti-vaqti bilan yangilang",
    old_password: "Joriy parol",
    new_password: "Yangi parol",
    confirm_password: "Yangi parol (takror)",
    update_password: "Parolni yangilash",
    weak: "Zaif",
    fair: "O'rtacha",
    good: "Yaxshi",
    strong: "Kuchli",
    matches: "Mos keladi",
    does_not_match: "Mos kelmaydi",
    security_tips: "Xavfsizlik maslahatlari",
    joined_date: "A'zo bo'lgan sana",
    last_login_date: "So'nggi kirish",
    system_text: "Tizim",
    role_capabilities: "ROLI IMKONIYATLARI",
    current_session: "JORIY SESSIYA",
    end_session: "Sessiyani yakunlash",
    return_admin: "Menejer paneliga qaytish",
    return_map: "Xaritaga qaytish",
    // Landing
    smart_control: "Aqlli boshqaruv",
    future: "Kelajak",
    parking_title: "Avtoturargohi",
    hero_desc: "Biznesingiz yoki dam olishingiz uchun eng zamonaviy turargoh. Real vaqtda band qilish va xavfsiz to'lovlar.",
    book_space: "Joy Band Qilish",
    view_map: "Xaritani ko'rish",
    parking_occupancy: "Turargoh bandligi",
    sales: "SAVDO",
    clients: "MIJOZLAR",
    our_advantages: "Afzalliklarimiz",
    advantages_desc: "SmartPark - bu shunchaki joy emas, bu sifat va texnologiya uyg'unligi.",
    pro_security: "Professional Himoya",
    pro_security_desc: "Barcha sektorlar 24/7 rejimida sun'iy intellekt yordamida nazorat qilinadi.",
    fast_booking: "Tezkor Bron",
    fast_booking_desc: "Navbat kutishga vaqt sarflamang. Telefoningiz orqali joyingizni oldindan band qiling.",
    smart_payment: "Aqlli To'lov",
    smart_payment_desc: "To'lovlar to'g'ridan-to'g'ri tizim orqali amalga oshiriladi va kvitansiya PDF darsida tayyor bo'ladi.",
    sector_map: "Xarita sektori",
    active_zone: "Faol yetkazib berish hududi",
    auth_client: "Tasdiqlangan Mijoz maqomi",
    login_btn: "Tizimga Kirish",
    // AdminReports
    bi_engine: "Ilg'or BI Dvigatel",
    decision_support: "Qarorlarni qo'llab-quvvatlash va vizual tahlil",
    excel_grid: "Excel Jadval",
    full_exec_pdf: "To'liq PDF Hisobot",
    avg_ticket: "O'rtacha Chipta",
    peak_hour: "Eng Faol Soat",
    realtime_load: "Real vaqtda yuklama",
    gross_total: "Jami yig'im (UZS)",
    per_booking: "Har bir bron uchun",
    highest_activity: "Eng yuqori faollik",
    peak_hour_analyzer: "Soatlar bo'yicha tahlil",
    arrival_dist: "Kelishlarning soatlar bo'yicha taqsimoti",
    activity_by_day: "Kunlik faollik",
    top_performance: "Eng yaxshi natija",
    branch_economics: "Filiallar iqtisodiyoti",
    revenue_by_branch: "Filiallar bo'yicha daromad taqqoslash",
    occupancy_hub: "Bandlik intensivligi",
    slots_occupied: "joy band",
    critical_load: "Kritik yuklama",
    optional_load: "Optimal yuklama",
    expand_view: "Kengaytirilgan ko'rinish",
    connect_master: "Asosiy boshqaruvga ulaning",
    report_generating: "Hisobot tayyorlanmoqda",
    report_ready: "Hisobot tayyor",
    // AdminDashboard
    command_center: "Boshqaruv Markazi v3.0",
    realtime_intel: "Real vaqt korxona razvedkasi",
    new_slot: "Yangi Slot",
    block_user: "Bloklash",
    broadcast: "E'lon",
    sync_data: "Yangilash",
    finance_pulse: "Moliya Impulsi",
    revenue_stream: "7 kunlik daromad oqimi tahlili",
    recent_activity: "Oxirgi Faoliyat",
    system_health: "Tizim Holati",
    cluster_ok: "Klaster: Ishlamoqda",
    api_latency: "API Kechikish",
    capacity_logic: "Sig'im Mantig'i",
    branch_metrics: "Filial Ko'rsatkichlari",
    view_all_branches: "Barcha Filiallarni Ko'rish",
    ai_insight: "SmartPark AI Tahlili",
    ai_insight_desc: "Tizim bugun soat 18:45 da eng yuqori bandlikni bashorat qilmoqda. Daromadni maksimal oshirish uchun VIP joylarni oldindan ajrating.",
    get_analysis: "To'liq Tahlil Olish",
    system_wide: "Tizim bo'yicha yuklama",
    active_branches: "Faol filiallar",
    net_total: "Jami (UZS)",
    verified_sessions: "Tasdiqlangan bronlar",
    // AdminCustomers
    loyalty_mesh: "Mijozlar Sadoqat Tarmog'i",
    customer_base: "Mijozlar Bazasi",
    crm_desc: "Korporativ Mijozlarni Boshqarish Tizimi (CRM)",
    search_profiles: "Mijoz qidirish...",
    total_assets: "Jami Mijozlar",
    verified_loyalty: "Tasdiqlangan Sadoqat",
    strategic_vips: "VIP Mijozlar",
    authorized_identity: "Foydalanuvchi",
    prime_asset: "Mashina",
    loyalty_status: "Holati",
    yield_col: "To'lov",
    protocol_col: "Amal",
    mesh_loading: "Yuklanmoqda...",
    status_active: "Faol",
    status_blocked: "Bloklangan",
    vip_node: "VIP",
    loyal_node: "Doimiy",
    customer_intel: "Mijoz Ma'lumotlari",
    engagement: "Bronlar",
    contribution: "Umumiy To'lov",
    asset_params: "Ma'lumotlar",
    edit_assets: "Tahrirlash",
    cancel_edit: "Bekor",
    mobile_link: "Telefon",
    plate_id: "Mashina raqami",
    update_assets: "Saqlash",
    prime_plate: "Asosiy Mashina Raqami",
    no_mobile: "Telefon kiritilmagan",
    unknown_asset: "NOMA'LUM",
    quarantine: "BLOKLASH",
    restore_access: "QAYTA OCHISH",
    access_restored: "Kirish tiklandi",
    user_quarantined: "Foydalanuvchi bloklandi",
    update_success: "Muvaffaqiyatli yangilandi",
    update_failed: "Yangilashda xatolik",
    intel_exported: "Ma'lumotlar eksport qilindi",
    account_active: "Hisob: Faol",
    account_suspended: "Hisob: Bloklangan",
    // AdminBookings
    monitoring_reservations: "Barcha bronlarni kuzatib borish",
    status_pending: "Kutilmoqda",
    status_completed: "Tugallandi",
    status_cancelled: "Bekor qilindi",
    filter_all: "Barchasi",
    slot_action: "Joy & Amal",
    user_col: "Foydalanuvchi",
    time_col: "Vaqt",
    status_col: "Holat",
    na: "Mavjud emas",
    // AdminNotifications
    communications_hub: "Xabarlar Markazi",
    admin_notifications_title: "Bildirishnomalar",
    monitoring_alerts: "Barcha xabarlar",
    history: "Tarix",
    no_notifications: "Bildirishnomalar topilmadi",
    mark_read2: "O'qilgan deb belgilash",
    read: "O'qildi",
    event_id: "Hodisa ID:",
    // AdminParkingLots
    branch_protocol: "Filial Parametrlari",
    architectural_viz: "Arxitektura Ko'rinishi",
    entity_name: "Filial Nomi",
    operational_hours: "Ish vaqti",
    location_address: "Manzil",
    contact_phone: "Aloqa Telefoni",
    coordinates: "Koordinatalar (Lat/Lng)",
    strategic_desc: "Strategik Tavsif",
    commit_changes: "O'ZGARISHLARNI SAQLASH",
    deploy_branch: "YANGI FILIAL QO'SHISH",
    branch_metrics_updated: "Filial ma'lumotlari yangilandi",
    new_branch_deployed: "Yangi filial qo'shildi",
    validation_failure: "Xatolik yuz berdi",
    terminate_branch_prompt: "Filialni o'chirishni tasdiqlaysizmi? Barcha bog'langan joylar o'chiriladi.",
    branch_archived: "Filial o'chirildi",
    access_denied: "Ruxsat etilmadi",
    multi_location_mesh: "Ko'p Filialli Tizim v3",
    branch_control: "Filiallar",
    enterprise_location_strategy: "Korporativ Joylashuv Strategiyasi",
    deploy_new_location: "Yangi Filial Qo'shish",
    operational_nodes: "Faol Filiallar",
    aggregate_capacity: "Umumiy Sig'im",
    total_yield: "Jami Daromad",
    no_asset_visual: "Rasm Yo'q",
    active_node: "Faol Filial",
    accumulated_uzs: "To'plangan (UZS)",
    manage_branch: "Boshqarish",
    // AdminPayments
    transact_audit: "Tranzaksiya Auditi",
    transaction_amount: "Tranzaksiya Summasi",
    verified_final: "Tasdiqlangan",
    pending_auth: "Kutilmoqda",
    technical_registry: "Texnik Ma'lumotlar",
    registry_id: "Reyestr ID",
    booking_link: "Bron havolasi",
    timestamp: "Vaqt",
    payment_meta: "To'lov Usuli",
    method: "Usul",
    electronic_terminal: "Elektron Terminal",
    audit_saved: "Audit hujjat saqlandi",
    audit_text: "Audit Matni",
    printing_ticket: "Chipta printerga yuborilmoqda...",
    print_ticket: "Chipta Chop Etish",
    revenue_monitoring_v3: "Daromad monitoringi v3",
    finance_command: "Moliya",
    transaction_audit_cashflow: "Tranzaksiyalar va Daromadlar",
    search_by_id: "ID qidirish...",
    gross_harvest: "Jami Daromad",
    all_time_net_income: "Barcha vaqtlardagi",
    mission_focus_month: "Shu Oy (Sof Foyda)",
    current_month_projection: "Joriy oy",
    todays_velocity: "Bugungi tushum",
    realtime_cashflow: "Pullar oqimi",
    financial_dynamics: "Moliyaviy dinamika",
    seven_day_trajectory: "7 kunlik ko'rsatkich",
    filter_paid: "To'langan",
    filter_pending: "Kutilmoqda",
    transaction_entity: "Tranzaksiya obyekti",
    monetary_value: "Qiymati",
    temporal_record: "Vaqt",
    status_matrix: "Holat",
    verification: "Tasdiq",
    digital_merchant_trace: "Raqamli tranzaksiya",
    system_time: "Tizim vaqti",
    status_success: "Muvaffaqiyatli",
    status_pending_matrix: "Kutilmoqda",
    export_ok: "Yuklab olindi",
    // Customer Dashboard
    user_sidebar_tag: "MIJOZ CRM",
    active_missions: "Xizmatdagi bronlar",
    total_contribution: "Jami kiritilgan sarmoya",
    loyalty_level: "Sodiqlik darajasi",
    total_bookings: "Jami kiritilgan yillar",
    my_bookings: "Mening bronlarim",
    payment_history: "To'lovlar tarixi",
    download_receipt: "PDF Chekni yuklash",
    no_bookings_yet: "Hozircha hech qanday bron topilmadi",
    no_payments_yet: "Hozircha hech qanday to'lov mavjud emas",
    client_dashboard_title: "MIJOZ BOSHQUROVI"
  },
  ru: {
    dashboard: "Панель управления",
    bookings: "Контроль броней",
    customers: "База клиентов",
    spaces: "Управление местами",
    parkingLots: "Филиалы",
    reports: "Отчеты",
    payments: "Платежи",
    notifications: "Уведомления",
    profile: "Профиль",
    logout: "Выйти",
    amal: "Действие",
    tahrirlash: "Изменить",
    o_chirish: "Удалить",
    qo_shish: "Добавить",
    saqlash: "Сохранить",
    bekor_qilish: "Отмена",
    barchasi: "Все",
    kutilmoqda: "Ожидание",
    faol: "Активно",
    tugallandi: "Завершено",
    bekor_qilindi: "Отменено",
    search: "Поиск...",
    revenue: "Общая выручка",
    occupancy: "Занятость",
    active_bookings: "Активные брони",
    total_spaces: "Всего мест",
    language: "Язык",
    theme: "Тема",
    dark_mode: "Темный режим",
    light_mode: "Светлый режим",
    error_loading: "Ошибка загрузки",
    name: "Имя",
    address: "Адрес",
    working_hours: "Рабочее время",
    phone: "Телефон",
    email: "Email",
    total: "Всего",
    occupied: "Занято",
    available: "Свободно",
    price: "Цена",
    type: "Тип",
    identifier: "Номер слота",
    status: "Статус",
    car: "Машина",
    user: "Пользователь",
    time: "Время",
    sum: "Сумма",
    trans_id: "ID транзакции",
    export: "Экспорт",
    map: "Карта",
    list: "Список",
    save_success: "Успешно сохранено",
    delete_confirm: "Вы действительно хотите удалить?",
    mark_all_read: "Прочитать все",
    // Profile
    personal_info: "Информация",
    security: "Безопасность",
    statistics: "Статистика",
    first_name: "Имя",
    last_name: "Фамилия",
    full_name: "Имя Фамилия",
    role: "Ваша роль",
    car_number_type: "Тип номера авто",
    individual: "Физическое лицо",
    legal_entity: "Юридическое лицо",
    individual_mode: "РЕЖИМ ФИЗИЧЕСКОГО ЛИЦА",
    legal_mode: "РЕЖИМ ЮРИДИЧЕСКОГО ЛИЦА",
    not_entered: "Не введено",
    change_password: "Изменить пароль",
    change_password_desc: "Периодически обновляйте пароль для усиления безопасности",
    old_password: "Текущий пароль",
    new_password: "Новый пароль",
    confirm_password: "Новый пароль (повторите)",
    update_password: "Обновить пароль",
    weak: "Слабый",
    fair: "Средний",
    good: "Хороший",
    strong: "Надежный",
    matches: "Совпадает",
    does_not_match: "Не совпадает",
    security_tips: "Советы по безопасности",
    joined_date: "Дата регистрации",
    last_login_date: "Последний вход",
    system_text: "Система",
    role_capabilities: "ВОЗМОЖНОСТИ РОЛИ",
    current_session: "ТЕКУЩАЯ СЕССИЯ",
    end_session: "Завершить сессию",
    return_admin: "Вернуться в панель менеджера",
    return_map: "Вернуться к карте",
    // Landing
    smart_control: "Умное управление",
    future: "Парковка",
    parking_title: "Будущего",
    hero_desc: "Самая современная парковка для вашего бизнеса или отдыха. Бронирование в реальном времени.",
    book_space: "Забронировать Место",
    view_map: "Карта Парковки",
    parking_occupancy: "Занятость парковки",
    sales: "ПРОДАЖИ",
    clients: "КЛИЕНТЫ",
    our_advantages: "Наши Преимущества",
    advantages_desc: "SmartPark - это сочетание качества и технологий.",
    pro_security: "Проф. Защита",
    pro_security_desc: "Все сектора контролируются в режиме 24/7 с помощью ИИ.",
    fast_booking: "Быстрая Бронь",
    fast_booking_desc: "Не тратьте время в очередях. Бронируйте через смартфон.",
    smart_payment: "Умная Оплата",
    smart_payment_desc: "Платежи осуществляются напрямую через систему.",
    sector_map: "Карта Секторов",
    active_zone: "Активная зона развертывания",
    auth_client: "Статус Авторизованного Клиента",
    login_btn: "Войти в систему",
    // AdminReports
    bi_engine: "Расширенный BI двигатель",
    decision_support: "Поддержка решений и визуальная аналитика",
    excel_grid: "Таблица Excel",
    full_exec_pdf: "Полный PDF Отчет",
    avg_ticket: "Средний чек",
    peak_hour: "Пиковый час",
    realtime_load: "Загрузка в реальном времени",
    gross_total: "Валовая выручка (UZS)",
    per_booking: "За бронь",
    highest_activity: "Наивысшая активность",
    peak_hour_analyzer: "Анализ по часам",
    arrival_dist: "Распределение прибытий по часам",
    activity_by_day: "Активность по дням",
    top_performance: "Лучший результат",
    branch_economics: "Экономика филиалов",
    revenue_by_branch: "Сравнение доходов по филиалам",
    occupancy_hub: "Интенсивность занятости",
    slots_occupied: "мест занято",
    critical_load: "Критическая нагрузка",
    optional_load: "Оптимальная нагрузка",
    expand_view: "Расширенный вид",
    connect_master: "Подключиться к главному управлению",
    report_generating: "Генерация отчета...",
    report_ready: "Отчет готов",
    // AdminDashboard
    command_center: "Центр управления v3.0",
    realtime_intel: "Разведка предприятия в реальном времени",
    new_slot: "Новое Место",
    block_user: "Заблокировать",
    broadcast: "Рассылка",
    sync_data: "Обновить",
    finance_pulse: "Финансовый Импульс",
    revenue_stream: "Анализ потока доходов за 7 дней",
    recent_activity: "Последняя Активность",
    system_health: "Состояние Системы",
    cluster_ok: "Кластер: Работает",
    api_latency: "Задержка API",
    capacity_logic: "Логика вместимости",
    branch_metrics: "Показатели Филиалов",
    view_all_branches: "Смотреть все филиалы",
    ai_insight: "SmartPark AI Анализ",
    ai_insight_desc: "Система прогнозирует пиковую занятость сегодня в 18:45. Зарезервируйте VIP места для максимизации дохода.",
    get_analysis: "Получить Полный Анализ",
    system_wide: "Общесистемная нагрузка",
    active_branches: "Активные филиалы",
    net_total: "Итого (UZS)",
    verified_sessions: "Подтверждённые брони",
    // AdminCustomers
    loyalty_mesh: "Сеть Лояльности Клиентов",
    customer_base: "База Клиентов",
    crm_desc: "Корпоративная Система Управления Клиентами (CRM)",
    search_profiles: "Поиск клиента...",
    total_assets: "Всего Клиентов",
    verified_loyalty: "Подтверждённые",
    strategic_vips: "VIP Клиенты",
    authorized_identity: "Пользователь",
    prime_asset: "Авто",
    loyalty_status: "Статус",
    yield_col: "Оплата",
    protocol_col: "Действие",
    mesh_loading: "Загрузка...",
    status_active: "Активен",
    status_blocked: "Заблокирован",
    vip_node: "VIP",
    loyal_node: "Постоянный",
    customer_intel: "Профиль Клиента",
    engagement: "Брони",
    contribution: "Общая Оплата",
    asset_params: "Данные",
    edit_assets: "Изменить",
    cancel_edit: "Отмена",
    mobile_link: "Телефон",
    plate_id: "Номер авто",
    update_assets: "Сохранить",
    prime_plate: "Номер Автомобиля",
    no_mobile: "Телефон не указан",
    unknown_asset: "НЕИЗВЕСТНО",
    quarantine: "ЗАБЛОКИРОВАТЬ",
    restore_access: "ВОССТАНОВИТЬ ДОСТУП",
    access_restored: "Доступ восстановлен",
    user_quarantined: "Пользователь заблокирован",
    update_success: "Успешно обновлено",
    update_failed: "Ошибка обновления",
    intel_exported: "Данные экспортированы",
    account_active: "Аккаунт: Активен",
    account_suspended: "Аккаунт: Заблокирован",
    // AdminBookings
    monitoring_reservations: "Отслеживание бронирований",
    status_pending: "В ожидании",
    status_completed: "Завершено",
    status_cancelled: "Отменено",
    filter_all: "Все",
    slot_action: "Место и действие",
    user_col: "Пользователь",
    time_col: "Время",
    status_col: "Статус",
    na: "Н/Д",
    // AdminNotifications
    communications_hub: "Центр Уведомлений",
    admin_notifications_title: "Уведомления",
    monitoring_alerts: "Сообщения",
    history: "История",
    no_notifications: "Нет уведомлений",
    mark_read2: "Отметить",
    read: "Прочитано",
    event_id: "ID События:",
    // AdminParkingLots
    branch_protocol: "Параметры Филиала",
    architectural_viz: "Архитектурный Выд",
    entity_name: "Название Филиала",
    operational_hours: "Часы работы",
    location_address: "Адрес",
    contact_phone: "Контактный Телефон",
    coordinates: "Координаты (Lat/Lng)",
    strategic_desc: "Описание",
    commit_changes: "СОХРАНИТЬ ИЗМЕНЕНИЯ",
    deploy_branch: "НОВЫЙ ФИЛИАЛ",
    branch_metrics_updated: "Обновлено",
    new_branch_deployed: "Создано",
    validation_failure: "Ошибка проверки",
    terminate_branch_prompt: "Удалить филиал? Все связанные места будут удалены.",
    branch_archived: "Удалено",
    access_denied: "Запрещено",
    multi_location_mesh: "Филиальная система v3",
    branch_control: "Филиалы",
    enterprise_location_strategy: "Стратегия Местоположения",
    deploy_new_location: "Добавить Филиал",
    operational_nodes: "Активные Филиалы",
    aggregate_capacity: "Вместимость",
    total_yield: "Общая прибыль",
    no_asset_visual: "Нет Изображения",
    active_node: "Активно",
    accumulated_uzs: "Накоплено (UZS)",
    manage_branch: "Управление",
    // AdminPayments
    transact_audit: "Аудит Транзакции",
    transaction_amount: "Сумма",
    verified_final: "Подтверждено",
    pending_auth: "Ожидается",
    technical_registry: "Данные",
    registry_id: "Реестр ID",
    booking_link: "Ссылка",
    timestamp: "Время",
    payment_meta: "Метод Оплаты",
    method: "Метод",
    electronic_terminal: "Терминал",
    audit_saved: "Сохранено",
    audit_text: "Текст",
    printing_ticket: "Печать...",
    print_ticket: "Распечатать",
    revenue_monitoring_v3: "Мониторинг доходов v3",
    finance_command: "Финансы",
    transaction_audit_cashflow: "Транзакции и Доходы",
    search_by_id: "Искать по ID...",
    gross_harvest: "Общий Доход",
    all_time_net_income: "За все время",
    mission_focus_month: "Этот Месяц",
    current_month_projection: "Показатель",
    todays_velocity: "Сегодняшний Доход",
    realtime_cashflow: "Денежный поток",
    financial_dynamics: "Динамика",
    seven_day_trajectory: "7-дневная траектория",
    filter_paid: "Оплачено",
    filter_pending: "Ожидается",
    transaction_entity: "Транзакция",
    monetary_value: "Сумма",
    temporal_record: "Время",
    status_matrix: "Статус",
    verification: "Проверка",
    digital_merchant_trace: "Записано",
    system_time: "Системное время",
    status_success: "Успех",
    status_pending_matrix: "В ожидании",
    export_ok: "Экспортировано",
    // Customer Dashboard
    user_sidebar_tag: "КЛИЕНТ CRM",
    active_missions: "Активные брони",
    total_contribution: "Общий вклад",
    loyalty_level: "Уровень лояльности",
    total_bookings: "Всего бронирований",
    my_bookings: "Мои брони",
    payment_history: "История платежей",
    download_receipt: "Скачать PDF Чек",
    no_bookings_yet: "Бронирований пока нет",
    no_payments_yet: "Платежей пока нет",
    client_dashboard_title: "ПАНЕЛЬ КЛИЕНТА"
  },
  en: {
    dashboard: "Dashboard",
    bookings: "Bookings",
    customers: "Customers",
    spaces: "Spaces",
    parkingLots: "Branches",
    reports: "Analytics",
    payments: "Payments",
    notifications: "Messages",
    profile: "Profile",
    logout: "Logout",
    amal: "Action",
    tahrirlash: "Edit",
    o_chirish: "Delete",
    qo_shish: "Add New",
    saqlash: "Save",
    bekor_qilish: "Cancel",
    barchasi: "All",
    kutilmoqda: "Pending",
    faol: "Active",
    tugallandi: "Completed",
    bekor_qilindi: "Cancelled",
    search: "Search...",
    revenue: "Total Revenue",
    occupancy: "Occupancy",
    active_bookings: "Active Bookings",
    total_spaces: "Total Spaces",
    language: "Language",
    theme: "Theme",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    error_loading: "Loading Error",
    name: "Name",
    address: "Address",
    working_hours: "Working Hours",
    phone: "Phone",
    email: "Email",
    total: "Total",
    occupied: "Occupied",
    available: "Available",
    price: "Price",
    type: "Type",
    identifier: "Slot ID",
    status: "Status",
    car: "Car",
    user: "User",
    time: "Time",
    sum: "Amount",
    trans_id: "Transaction ID",
    export: "Export",
    map: "Map",
    list: "List",
    save_success: "Successfully saved",
    delete_confirm: "Are you sure you want to delete?",
    mark_all_read: "Mark all read",
    // Profile
    personal_info: "Information",
    security: "Security",
    statistics: "Statistics",
    first_name: "First Name",
    last_name: "Last Name",
    full_name: "Full Name",
    role: "System Role",
    car_number_type: "Car Plate Type",
    individual: "Individual",
    legal_entity: "Legal Entity",
    individual_mode: "INDIVIDUAL MODE",
    legal_mode: "LEGAL ENTITY MODE",
    not_entered: "Not entered",
    change_password: "Change Password",
    change_password_desc: "Update your password periodically to increase security",
    old_password: "Current Password",
    new_password: "New Password",
    confirm_password: "New Password (repeat)",
    update_password: "Update Password",
    weak: "Weak",
    fair: "Fair",
    good: "Good",
    strong: "Strong",
    matches: "Matches",
    does_not_match: "Does not match",
    security_tips: "Security Tips",
    joined_date: "Joined Date",
    last_login_date: "Last Login",
    system_text: "System",
    role_capabilities: "ROLE CAPABILITIES",
    current_session: "CURRENT SESSION",
    end_session: "End Session",
    return_admin: "Return to Manager Panel",
    return_map: "Return to Sector Map",
    // Landing
    smart_control: "Smart Control",
    future: "The Parking of",
    parking_title: "The Future",
    hero_desc: "The most modern parking for your business or leisure. Real-time booking and secure payments.",
    book_space: "Book Space",
    view_map: "View Map",
    parking_occupancy: "Parking Occupancy",
    sales: "SALES",
    clients: "CLIENTS",
    our_advantages: "Our Advantages",
    advantages_desc: "SmartPark is not just a place, it's a blend of quality and technology.",
    pro_security: "Pro Security",
    pro_security_desc: "All sectors are monitored 24/7 using artificial intelligence.",
    fast_booking: "Fast Booking",
    fast_booking_desc: "Don't waste time in queues. Book in advance via your phone.",
    smart_payment: "Smart Payment",
    smart_payment_desc: "Payments are processed directly via the system.",
    sector_map: "Sector Map",
    active_zone: "Active Deployment Zone",
    auth_client: "Authorized Client Status",
    login_btn: "Login to System",
    // AdminReports
    bi_engine: "Advanced BI Engine",
    decision_support: "Decision Support & Visual Analytics",
    excel_grid: "Excel Grid",
    full_exec_pdf: "Full Executive PDF",
    avg_ticket: "Average Ticket",
    peak_hour: "Peak Hour",
    realtime_load: "Real-time Load",
    gross_total: "Gross Total (UZS)",
    per_booking: "Per Booking",
    highest_activity: "Highest Activity",
    peak_hour_analyzer: "Peak Hour Analyzer",
    arrival_dist: "Arrival distribution by hour (00-23)",
    activity_by_day: "Activity by Day",
    top_performance: "Top Performance",
    branch_economics: "Branch Economics",
    revenue_by_branch: "Revenue Comparison by Branch",
    occupancy_hub: "Occupancy Intensity Hub",
    slots_occupied: "slots occupied",
    critical_load: "CRITICAL LOAD",
    optional_load: "OPTIMAL LOAD",
    expand_view: "Expand Strategic View",
    connect_master: "Connect to master lot manager",
    report_generating: "Generating Report...",
    report_ready: "Report Ready",
    // AdminDashboard
    command_center: "Command Center v3.0",
    realtime_intel: "Real-time Enterprise Intelligence",
    new_slot: "New Slot",
    block_user: "Block User",
    broadcast: "Broadcast",
    sync_data: "Sync Data",
    finance_pulse: "Finance Pulse",
    revenue_stream: "Revenue stream analysis over 7 days",
    recent_activity: "Recent Activity",
    system_health: "System Health",
    cluster_ok: "Cluster: Operational",
    api_latency: "API Latency",
    capacity_logic: "Capacity Logic",
    branch_metrics: "Branch Metrics",
    view_all_branches: "View All Branches",
    ai_insight: "SmartPark AI Insight",
    ai_insight_desc: "System predicts peak occupancy at 18:45 today. Pre-allocate VIP slots to maximize revenue.",
    get_analysis: "Get Full Analysis",
    system_wide: "System-wide Load",
    active_branches: "Active Branches",
    net_total: "Net Total (UZS)",
    verified_sessions: "Verified Sessions",
    // AdminCustomers
    loyalty_mesh: "Customer Loyalty Mesh",
    customer_base: "Customer Base",
    crm_desc: "Enterprise Customer Relationship Management (CRM)",
    search_profiles: "Search profiles...",
    total_assets: "Total Clients",
    verified_loyalty: "Verified Loyalty",
    strategic_vips: "Strategic VIPs",
    authorized_identity: "Identity",
    prime_asset: "Vehicle",
    loyalty_status: "Status",
    yield_col: "Payment",
    protocol_col: "Action",
    mesh_loading: "Loading...",
    status_active: "Active",
    status_blocked: "Blocked",
    vip_node: "VIP",
    loyal_node: "Loyal",
    customer_intel: "Customer Intelligence",
    engagement: "Bookings",
    contribution: "Total Payment",
    asset_params: "Information",
    edit_assets: "Edit",
    cancel_edit: "Cancel",
    mobile_link: "Phone",
    plate_id: "Car Plate",
    update_assets: "Save",
    prime_plate: "Primary Car Plate",
    no_mobile: "No phone",
    unknown_asset: "UNKNOWN",
    quarantine: "BLOCK USER",
    restore_access: "RESTORE ACCESS",
    access_restored: "Access Restored",
    user_quarantined: "User Blocked",
    update_success: "Successfully Updated",
    update_failed: "Update Failed",
    intel_exported: "Data Exported",
    account_active: "Account: Active",
    account_suspended: "Account: Suspended",
    // AdminBookings
    monitoring_reservations: "Monitoring all reservations",
    status_pending: "Pending",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
    filter_all: "All",
    slot_action: "Slot & Action",
    user_col: "User",
    time_col: "Time",
    status_col: "Status",
    na: "N/A",
    // AdminNotifications
    communications_hub: "Communications Hub",
    admin_notifications_title: "Notifications",
    monitoring_alerts: "Monitoring all system-wide alerts and messages",
    history: "History",
    no_notifications: "No notifications found",
    mark_read2: "Mark Read",
    read: "Read",
    event_id: "Event ID:",
    // AdminParkingLots
    branch_protocol: "Branch Protocol",
    architectural_viz: "Architectural Visualization",
    entity_name: "Entity Name",
    operational_hours: "Operational Hours",
    location_address: "Location Address",
    contact_phone: "Contact Phone",
    coordinates: "Coordinates (Lat/Lng)",
    strategic_desc: "Strategic Description",
    commit_changes: "COMMIT CHANGES",
    deploy_branch: "DEPLOY BRANCH",
    branch_metrics_updated: "Branch Metrics Updated",
    new_branch_deployed: "New Branch Deployed",
    validation_failure: "Validation Failure",
    terminate_branch_prompt: "Terminate Branch Protocol? All associated spaces will be archived.",
    branch_archived: "Branch Archived",
    access_denied: "Access Denied",
    multi_location_mesh: "Multi-Location Mesh v3",
    branch_control: "Branch Control",
    enterprise_location_strategy: "Enterprise Location Strategy & Resource Allocation",
    deploy_new_location: "Deploy New Location",
    operational_nodes: "Operational Nodes",
    aggregate_capacity: "Aggregate Capacity",
    total_yield: "Total Yield",
    no_asset_visual: "No Asset Visual",
    active_node: "Active Node",
    accumulated_uzs: "Accumulated UZS",
    manage_branch: "Manage Branch",
    // AdminPayments
    transact_audit: "Transact Audit",
    transaction_amount: "Transaction Amount",
    verified_final: "Verified & Final",
    pending_auth: "Pending Authorization",
    technical_registry: "Technical Registry",
    registry_id: "Registry ID",
    booking_link: "Booking Link",
    timestamp: "Timestamp",
    payment_meta: "Payment Meta",
    method: "Method",
    electronic_terminal: "Electronic Terminal",
    audit_saved: "Audit text saved",
    audit_text: "Audit Text",
    printing_ticket: "Ticket sent to printer...",
    print_ticket: "Print Ticket",
    revenue_monitoring_v3: "Revenue monitoring v3",
    finance_command: "Finance Command",
    transaction_audit_cashflow: "Transaction Audit & Cashflow Intelligence",
    search_by_id: "Search by ID...",
    gross_harvest: "Gross Harvest",
    all_time_net_income: "All-time Net Income",
    mission_focus_month: "Mission Focus (Month)",
    current_month_projection: "Current Month Projection",
    todays_velocity: "Today's Velocity",
    realtime_cashflow: "Real-time Cashflow",
    financial_dynamics: "Financial Dynamics",
    seven_day_trajectory: "7-Day revenue stream trajectory",
    filter_paid: "Paid",
    filter_pending: "Pending",
    transaction_entity: "Transaction Entity",
    monetary_value: "Monetary Value",
    temporal_record: "Temporal Record",
    status_matrix: "Status Matrix",
    verification: "Verification",
    digital_merchant_trace: "Digital Merchant Trace",
    system_time: "System Time",
    status_success: "Success",
    status_pending_matrix: "Pending",
    export_ok: "Export OK",
    // Customer Dashboard
    user_sidebar_tag: "CLIENT CRM",
    active_missions: "Active Missions",
    total_contribution: "Total Contribution",
    loyalty_level: "Loyalty Level",
    total_bookings: "Total Deployments",
    my_bookings: "My Bookings",
    payment_history: "Payment History",
    download_receipt: "Download PDF Receipt",
    no_bookings_yet: "No bookings found yet",
    no_payments_yet: "No payments found yet",
    client_dashboard_title: "CLIENT DASHBOARD"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'uz');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
